# Generated by Django 4.0.6 on 2022-07-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposta',
            options={'ordering': ['-data'], 'verbose_name': 'Proposta', 'verbose_name_plural': 'Propostas'},
        ),
        migrations.RenameField(
            model_name='proposta',
            old_name='dominio_login',
            new_name='dominio_login',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='login',
        ),
        migrations.AddField(
            model_name='proposta',
            name='login',
            field=models.CharField(blank=True, max_length=30, verbose_name='Login'),
        ),
    ]
